# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'QwQ' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QwQ

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  pod 'SDWebImage/Core'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FirebaseFirestoreSwift'

  target 'QwQTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QwQUITests' do
    # Pods for testing
  end

end
