# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QwQ-restaurant' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QwQ-restaurant

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  pod 'SDWebImage/Core'

  target 'QwQ-restaurantTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QwQ-restaurantUITests' do
    # Pods for testing
  end

	end
